FROM amazoncorretto:11-alpine-jdk // de que imagen partimos
MAINTAINER Gerino Enzo // creador del proyecto
COPY // copia el empaquetado a github
ENTRYPOINT // es la instruccion que se va a ejecutar primero  
